name: Tests

on:
    push:
        branches:        # Run tests when commits are pushed to these branches in your repo
            - master
    pull_request:        # Run tests when pull requests are made on these branches in your repo
        branches:
            - master

jobs:
    call-tests:
        uses: phpbb-extensions/test-framework/.github/workflows/tests.yml@3.3.x
        with:
            EXTNAME: phpbbmodders/trackers   # Your extension vendor/package name

            # OPTIONAL CONFIGURATIONS BELOW
            # The following arguments are optional and can be omitted if not needed.

            # The phpBB branch to use when running tests.
            # Default is '3.3.x', which this framework is designed for.
            # If using a different branch, ensure it's compatible with 3.3.x.
            # To test with phpBB's master branch, refer to the Branches section of this README.
            # Default: '3.3.x'
            PHPBB_BRANCH: '3.3.x'

            # Run phpBB's EPV (Extension Pre Validator)? 1 (yes) or 0 (no)
            # Default: 1
            EPV: 1

            # Check for files with executable permissions? 1 (yes) or 0 (no)
            # Default: 1
            EXECUTABLE_FILES: 1

            # Remove embedded ICC profiles from images? 1 (yes) or 0 (no)
            # Default: 1
            IMAGE_ICC: 1

            # Run CodeSniffer to detect PHP code style issues? 1 (yes) or 0 (no)
            # Default: 1
            SNIFF: 1

            # Run MySQL/MariaDB tests? 1 (yes) or 0 (no)
            # Default: 1
            RUN_MYSQL_JOBS: 0

            # Run PostgreSQL tests? 1 (yes) or 0 (no)
            # Default: 1
            RUN_PGSQL_JOBS: 0

            # Run MSSQL and SQLite3 tests? 1 (yes) or 0 (no)
            # Default: 1
            RUN_MSSQL_JOBS: 0

            # Run Windows IIS & PostgreSQL tests? 1 (yes) or 0 (no)
            # Default: 1
            RUN_WINDOWS_JOBS: 0

            # Run functional tests if you have them? 1 (yes) or 0 (no)
            # Default: 1
            RUN_FUNCTIONAL_TESTS: 0

            # Install NPM dependencies (if your extension relies on them)? 1 (yes) or 0 (no)
            # Default: 0
            RUN_NPM_INSTALL: 0

            # Install Composer dependencies (if your extension relies on them)? 1 (yes) or 0 (no)
            # Default: 0
            RUN_COMPOSER_INSTALL: 0

            # CUSTOMISE PHP VERSIONS
            # To override the default PHP versions tested (7.2 through 8.4):

            # Preferred PHP version used for all test jobs.
            # Default: '7.2'
            PRIMARY_PHP_VERSION: '8.1'

            # The MySQL and PostgreSQL jobs run tests across multiple PHP versions.
            # List the PHP versions you want your extension tested with.
            # Default: '["7.2", "7.3", "7.4", "8.0", "8.1", "8.2", "8.3", "8.4"]'
            PHP_VERSION_MATRIX: '["8.1", "8.1", "8.2", "8.3", "8.4"]'

            # Generate a code coverage report (see documentation below)? 1 (yes) or 0 (no)
            # Default: 0
            CODECOV: 0
